### PR TITLE
1.1 bug fixes and testing

### PR DESCRIPTION
**Pull request by CliffracerMerchant**
There are still unresolved bugs that need to be fixed before the 1.1 release, however the pending Jetpack Compose migration should render most of them obselete.

### CODE REVIEW

**Comment by istudyatuni** [comment]
Hi! Are you planning on releasing this?

**Comment by CliffracerMerchant** [comment]
I was planning on migrating the app to compose, and releasing it then. I ended up working the past few months on feature requests for my other app, so I haven't been able to work on this. I actually was just about to start work on the compose migration again, although it'll probably still be a while before it's ready. I could release an alpha build from the state the app was in when this PR was merged, but there is at least one minor-ish bug where the navigation indicator doesn't match the actual navigation state when the activity is recreated when viewing the settings screen. If you want me to release an alpha build anyways so you can use it now, let me know.

**Comment by istudyatuni** [comment]
Although the bug sounds a bit annoying, it would be great to see an alpha build!

**Comment by CliffracerMerchant** [comment]
I made a [v1.1 alpha release here](https://github.com/CliffracerMerchant/BootyCrate/releases/tag/v1.1-alpha). My self signed APK will have a different signing certificate than the one on the Play store. If you already have an installation from the Play store, you'll have to uninstall it first to install the APK on the release page (you shouldn't lose any of your in app data). And once I eventually get the update onto the Play store, you'll have to uninstall this APK before you can install it off of the Play store again. Sorry I guess I should have made sure you knew all of that before I offered to release it, but unfortunately that's how it works with signed APKs.

About the bug, it's been a while but iirc it only happens when you enter the app settings page from the inventory page, then rotate the screen, then back out of the settings to the inventory screen again.

**Comment by istudyatuni** [comment]
I previously installed a program from GitHub release, so no problem with signing :)

About the bug - I cannot rotate the screen at all 🤔 My phone - Google Pixel 5a, android 13

**Comment by CliffracerMerchant** [comment]
I think I disabled landscape until I could get the bug figured out? To be honest it was several months ago, so I'm not really sure. I definitely plan to allow landscape mode in the next update.

**Comment by istudyatuni** [comment]
That's fine, I don't think it's useful, at least for me.

**Pull request merged**
